runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /
    static_files: build/index.html
    upload: www/index.html

  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)

skip_files:
  - ^node_modules$
  - node_modules
  - .cache
  - src
  - template
