---
AWSTemplateFormatVersion: "2010-09-09"
Description: The AWS CloudFormation template for Website prototyping
Parameters:
  OriginName:
    Type: String
    Description: Name of the prototyping url you want to use (e.g. *.site.getdiff.app)
  AliasName:
    Type: String
    Description: Name of the prototyping url you want to use (e.g. *.site.getdiff.app)
  Stage:
    Type: String
    Description: What stage we are deploying to
Resources:
  # Route53 Record
  Route53RecordSet:
    Type: AWS::Route53::RecordSet
    DependsOn: CloudFrontDistribution
    Properties:
      Name: !Ref AliasName
      HostedZoneId: !ImportValue getdiff-hostedzone
      Type: A
      TTL: "300"
      AliasTarget:
        HostedZoneId: !ImportValue getdiff-hostedzone
        DNSName: !Ref CloudFrontDistribution

  # Cloudfront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        PriceClass: PriceClass_100
        Aliases:
          - !Ref AliasName
        ViewerCertificate:
          AcmCertificateArn: !ImportValue getdiff-acmcertificate
          SslSupportMethod: sni-only
        HttpVersion: http2
        Enabled: "true"
        Comment: "Lambda@edge distriubtion for protocol sites"
        Origins:
          - DomainName:
              Ref: OriginName
            Id: "ProtocolSiteDistribution"
            CustomOriginConfig:
              OriginSSLProtocols:
                - TLSv1.2
                - TLSv1.1
              OriginProtocolPolicy: https-only
            OriginCustomHeaders:
              - HeaderName: "x-proxy"
                HeaderValue: "getdiff"
        DefaultCacheBehavior:
          TargetOriginId: "ProtocolSiteDistribution"
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          ForwardedValues:
            QueryString: "true"
            Headers:
              - CloudFront-Forwarded-Proto
              - Host
              - Origin
              - x-forwarded-host
            Cookies:
              Forward: all
          MinTTL: 0
          MaxTTL: 30
          DefaultTTL: 0
          Compress: true
      Tags:
        - Key: STAGE
          Value: !Ref Stage
        - Key: APP
          Value: getdiff
Outputs:
  CloudFrontDistribution:
    Value:
      Ref: CloudFrontDistribution
    Export:
      Name: getdiff-cloudfront-clientbridge
  Route53RecordSet:
    Value:
      Ref: Route53RecordSet
    Export:
      Name: getdiff-route53-clientbridge-record
