---
AWSTemplateFormatVersion: "2010-09-09"
Description: The AWS CloudFormation template for getdiff main site
Parameters:
  OriginName:
    Type: String
    Description: Name of the prototyping url you want to use (e.g. *.site.getdiff.app)
  AliasNames:
    Type: CommaDelimitedList
    Description: Name of the prototyping url you want to use (e.g. *.site.getdiff.app)
  Stage:
    Type: String
    Description: What stage we are deploying to

Resources:
  # Record on Route53 that handles routing to our distribution
  Route53RecordSet:
    Type: AWS::Route53::RecordSet
    DependsOn: CloudFrontDistribution
    Properties:
      Name: !Ref OriginName
      HostedZoneId: !ImportValue getdiff-hostedzone
      Type: A
      TTL: "300"
      AliasTarget:
        HostedZoneId: !ImportValue getdiff-hostedzone
        DNSName: !Ref CloudFrontDistribution

  # access identify for cloudfront
  cloudfrontoriginaccessidentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: CloudFront OAI for getdiff s3

  # Cloudfront distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        PriceClass: PriceClass_100
        Origins:
          - DomainName:
              !Join [
                ".",
                [!ImportValue "getdiff-s3-client", "s3.amazonaws.com"],
              ]
            Id: ClientS3Origin
            S3OriginConfig:
              OriginAccessIdentity:
                !Join [
                  "",
                  [
                    "origin-access-identity/cloudfront/",
                    !Ref cloudfrontoriginaccessidentity,
                  ],
                ]
        ViewerCertificate:
          AcmCertificateArn: !ImportValue "getdiff-acmcertificate"
          SslSupportMethod: sni-only
        HttpVersion: http2
        Enabled: "true"
        Comment: "S3 Origin for the website"
        DefaultRootObject: index.html
        Aliases: !Ref AliasNames
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          TargetOriginId: ClientS3Origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: "true"
            Cookies:
              Forward: all
          MinTTL: 300
          MaxTTL: 600
          DefaultTTL: 300
          Compress: true
        CustomErrorResponses:
          - ErrorCode: "404"
            ResponsePagePath: "/index.html"
            ResponseCode: "200"
            ErrorCachingMinTTL: "0"
          - ErrorCode: "403"
            ResponsePagePath: "/index.html"
            ResponseCode: "200"
            ErrorCachingMinTTL: "0"
      Tags:
        - Key: STAGE
          Value: !Ref Stage
        - Key: APP
          Value: getdiff
Outputs:
  CloudFrontDistribution:
    Value:
      Ref: CloudFrontDistribution
    Export:
      Name: getdiff-cloudfront-client
  Route53RecordSet:
    Value:
      Ref: Route53RecordSet
    Export:
      Name: getdiff-route53-client-record
