---
AWSTemplateFormatVersion: "2010-09-09"
Description: The AWS CloudFormation template for Website prototyping
Parameters:
  BucketName:
    Type: String
    Description: Name of the prototyping url you want to use (e.g. *.site.getdiff.app)
  Stage:
    Type: String
    Description: What stage we are deploying to

Resources:
  # Bucket
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicRead
      Tags:
        - Key: STAGE
          Value: !Ref Stage
        - Key: APP
          Value: getdiff
    DeletionPolicy: Retain

  # Bucket Policy
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Id: S3BucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Join ["", ["arn:aws:s3:::", !Ref S3Bucket, "/*"]]

Outputs:
  getdiffClientS3bucket:
    Value:
      Ref: S3Bucket
    Export:
      Name: "getdiff-s3-clientbridge"
